#!/bin/bash

#first we make it an executable
if [ ! -x "$0" ]; then
    chmod +x "$0"
    echo "Created executable installation file."
    bash "$0"
    exit 0
fi

echo "Installing iterm2..."
brew install --cask iterm2
echo "Finished installing iterm2."

echo "Installing neovim from source..."
# curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-x86_64.tar.gz
# tar xzf nvim-macos-x86_64.tar.gz
# mv nvim-macos-x86_64 ~/
# rm -r nvim-macos-x86_64.tar.gz
brew install neovim
echo "Finished installing neovim."

echo "Installing latest nodejs and npm..."
# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
# in lieu of restarting the shell
\. "$HOME/.nvm/nvm.sh"
# Download and install Node.js:
nvm install 22
echo "Finished installing latest nodejs"



echo "Installing nodejs, git, packer and zsh..."
brew install git
brew tap hashicorp/tap
brew install hashicorp/tap/packer
brew upgrade hashicorp/tap/packer
brew install zsh
echo "All apt dependencies installed."

echo "Making zsh default shell..."
chsh -s /usr/local/bin/zsh
echo "Default shell set to zsh."

echo "Downloading oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo "Finished downloading oh-my-zsh."

echo "Installing zsh-autosuggestions..."
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
echo "Finished installing zsh autosuggestions."

echo "Installing zsh-autocomplete..."
git clone https://github.com/marlonrichert/zsh-autocomplete.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autocomplete
echo "Finished installing zsh autocomplete."

echo "Clonining zsh-syntax-highlighting..."
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
echo "Finished cloning zsh-syntax-highlighting."

echo "Installing zsh-powerlevel10k..."
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
echo "Finished installing zsh-powerlevel10k."

echo "Installing nerdfonts..."
brew install font-hack-nerd-font
echo "Finished installing nerdfonts."


echo "Transferring .dotfiles..."
cp ~/.dotfiles/.zshrc ~/.zshrc
cp -r ~/.dotfiles/.config/nvim ~/.config/nvim
cp -r ~/.dotfiles/.config/zsh ~/.config/zsh
# echo alias vim="nvim" >> ~/.zshrc
echo "Finished transferring .dotfiles."

zsh ~/.zshrc
#source ~/.config/nvim/init.lua
#source ~/.config/nvim/lua/gunnin/init.lua
#source ~/.config/nvim/lua/gunnin/packer.lua
#source ~/.config/nvim/lua/gunnin/set.lua
#source ~/.config/nvim/lua/gunnin/remap.lua

echo "Installing latest nodejs and npm..."
# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
# in lieu of restarting the shell
\. "$HOME/.nvm/nvm.sh"
# Download and install Node.js:
nvm install 22
echo "Finished installing latest nodejs"


echo "To finalize vim installation. Navigate to ~/.config/nvim/
and simply :PackerInstall and :PackerSync inside nvim."
echo "and..."
echo "To finalize oh-my-zsh installation, change font to nerdfont (FiraMono), 
restart terminal, and proceed with following the instructions in the terminal."
